// Code generated by "stringer -output=stringergen_bit.go -bitflag -type=CodeComplete_Flags,CompletionContext,DeclQualifierKind,DiagnosticDisplayOptions,GlobalOptFlags,TranslationUnit_Flags,PropertyAttrKind,SymbolRole"; DO NOT EDIT.

package clang

var _CodeComplete_Flags_stringer = _stringerBitflagCache{
	sb: _stringerBitflag{
		typename: "CodeComplete_Flags",
		zero:     "CodeComplete_Flags(0)",
		first:    uint64(1),
		names:    "CodeComplete_IncludeMacrosCodeComplete_IncludeCodePatternsCodeComplete_IncludeBriefCommentsCodeComplete_SkipPreambleCodeComplete_IncludeCompletionsWithFixIts",
		offsets:  []uint8{26, 32, 33, 25, 41},
	},
}

func (m CodeComplete_Flags) String() string {
	return _CodeComplete_Flags_stringer.mstring(uint64(m))
}

var _CompletionContext_stringer = _stringerBitflagCache{
	sb: _stringerBitflag{
		typename: "CompletionContext",
		zero:     "CompletionContext_Unexposed",
		first:    uint64(1),
		names:    "CompletionContext_AnyTypeCompletionContext_AnyValueCompletionContext_ObjCObjectValueCompletionContext_ObjCSelectorValueCompletionContext_CXXClassTypeValueCompletionContext_DotMemberAccessCompletionContext_ArrowMemberAccessCompletionContext_ObjCPropertyAccessCompletionContext_EnumTagCompletionContext_UnionTagCompletionContext_StructTagCompletionContext_ClassTagCompletionContext_NamespaceCompletionContext_NestedNameSpecifierCompletionContext_ObjCInterfaceCompletionContext_ObjCProtocolCompletionContext_ObjCCategoryCompletionContext_ObjCInstanceMessageCompletionContext_ObjCClassMessageCompletionContext_ObjCSelectorNameCompletionContext_MacroNameCompletionContext_NaturalLanguage",
		offsets:  []uint8{25, 26, 33, 35, 35, 33, 35, 36, 25, 26, 27, 26, 27, 37, 31, 30, 30, 37, 34, 34, 27, 33},
	},
}

func (m CompletionContext) String() string {
	return _CompletionContext_stringer.mstring(uint64(m))
}

var _DeclQualifierKind_stringer = _stringerBitflagCache{
	sb: _stringerBitflag{
		typename: "DeclQualifierKind",
		zero:     "DeclQualifierKind(0)",
		first:    uint64(1),
		names:    "DeclQualifier_InDeclQualifier_InoutDeclQualifier_OutDeclQualifier_BycopyDeclQualifier_ByrefDeclQualifier_Oneway",
		offsets:  []uint8{16, 19, 17, 20, 19, 20},
	},
}

func (m DeclQualifierKind) String() string {
	return _DeclQualifierKind_stringer.mstring(uint64(m))
}

var _DiagnosticDisplayOptions_stringer = _stringerBitflagCache{
	sb: _stringerBitflag{
		typename: "DiagnosticDisplayOptions",
		zero:     "DiagnosticDisplayOptions(0)",
		first:    uint64(1),
		names:    "Diagnostic_DisplaySourceLocationDiagnostic_DisplayColumnDiagnostic_DisplaySourceRangesDiagnostic_DisplayOptionDiagnostic_DisplayCategoryIdDiagnostic_DisplayCategoryName",
		offsets:  []uint8{32, 24, 30, 24, 28, 30},
	},
}

func (m DiagnosticDisplayOptions) String() string {
	return _DiagnosticDisplayOptions_stringer.mstring(uint64(m))
}

var _GlobalOptFlags_stringer = _stringerBitflagCache{
	sb: _stringerBitflag{
		typename: "GlobalOptFlags",
		zero:     "GlobalOpt_None",
		first:    uint64(1),
		names:    "GlobalOpt_ThreadBackgroundPriorityForIndexingGlobalOpt_ThreadBackgroundPriorityForEditing",
		offsets:  []uint8{45, 44},
	},
}

func (m GlobalOptFlags) String() string {
	return _GlobalOptFlags_stringer.mstring(uint64(m))
}

var _TranslationUnit_Flags_stringer = _stringerBitflagCache{
	sb: _stringerBitflag{
		typename: "TranslationUnit_Flags",
		zero:     "TranslationUnit_None",
		first:    uint64(1),
		names:    "TranslationUnit_DetailedPreprocessingRecordTranslationUnit_IncompleteTranslationUnit_PrecompiledPreambleTranslationUnit_CacheCompletionResultsTranslationUnit_ForSerializationTranslationUnit_CXXChainedPCHTranslationUnit_SkipFunctionBodiesTranslationUnit_IncludeBriefCommentsInCodeCompletionTranslationUnit_CreatePreambleOnFirstParseTranslationUnit_KeepGoingTranslationUnit_SingleFileParseTranslationUnit_LimitSkipFunctionBodiesToPreamble",
		offsets:  []uint8{43, 26, 35, 38, 32, 29, 34, 52, 42, 25, 31, 49},
	},
}

func (m TranslationUnit_Flags) String() string {
	return _TranslationUnit_Flags_stringer.mstring(uint64(m))
}

var _PropertyAttrKind_stringer = _stringerBitflagCache{
	sb: _stringerBitflag{
		typename: "PropertyAttrKind",
		zero:     "PropertyAttr_noattr",
		first:    uint64(1),
		names:    "PropertyAttr_readonlyPropertyAttr_getterPropertyAttr_assignPropertyAttr_readwritePropertyAttr_retainPropertyAttr_copyPropertyAttr_nonatomicPropertyAttr_setterPropertyAttr_atomicPropertyAttr_weakPropertyAttr_strongPropertyAttr_unsafe_unretainedPropertyAttr_class",
		offsets:  []uint8{21, 19, 19, 22, 19, 17, 22, 19, 19, 17, 19, 30, 18},
	},
}

func (m PropertyAttrKind) String() string {
	return _PropertyAttrKind_stringer.mstring(uint64(m))
}

var _SymbolRole_stringer = _stringerBitflagCache{
	sb: _stringerBitflag{
		typename: "SymbolRole",
		zero:     "SymbolRole_None",
		first:    uint64(1),
		names:    "SymbolRole_DeclarationSymbolRole_DefinitionSymbolRole_ReferenceSymbolRole_ReadSymbolRole_WriteSymbolRole_CallSymbolRole_DynamicSymbolRole_AddressOfSymbolRole_Implicit",
		offsets:  []uint8{22, 21, 20, 15, 16, 15, 18, 20, 19},
	},
}

func (m SymbolRole) String() string {
	return _SymbolRole_stringer.mstring(uint64(m))
}
