// Code generated by "stringer -type=Property"; DO NOT EDIT.

package printing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Indentation-0]
	_ = x[SuppressSpecifiers-1]
	_ = x[SuppressTagKeyword-2]
	_ = x[IncludeTagDefinition-3]
	_ = x[SuppressScope-4]
	_ = x[SuppressUnwrittenScope-5]
	_ = x[SuppressInitializers-6]
	_ = x[ConstantArraySizeAsWritten-7]
	_ = x[AnonymousTagLocations-8]
	_ = x[SuppressStrongLifetime-9]
	_ = x[SuppressLifetimeQualifiers-10]
	_ = x[SuppressTemplateArgsInCXXConstructors-11]
	_ = x[Bool-12]
	_ = x[Restrict-13]
	_ = x[Alignof-14]
	_ = x[UnderscoreAlignof-15]
	_ = x[UseVoidForZeroParams-16]
	_ = x[TerseOutput-17]
	_ = x[PolishForDeclaration-18]
	_ = x[Half-19]
	_ = x[MSWChar-20]
	_ = x[IncludeNewlines-21]
	_ = x[MSVCFormatting-22]
	_ = x[ConstantsAsWritten-23]
	_ = x[SuppressImplicitBase-24]
	_ = x[FullyQualifiedName-25]
}

const _Property_name = "IndentationSuppressSpecifiersSuppressTagKeywordIncludeTagDefinitionSuppressScopeSuppressUnwrittenScopeSuppressInitializersConstantArraySizeAsWrittenAnonymousTagLocationsSuppressStrongLifetimeSuppressLifetimeQualifiersSuppressTemplateArgsInCXXConstructorsBoolRestrictAlignofUnderscoreAlignofUseVoidForZeroParamsTerseOutputPolishForDeclarationHalfMSWCharIncludeNewlinesMSVCFormattingConstantsAsWrittenSuppressImplicitBaseFullyQualifiedName"

var _Property_index = [...]uint16{0, 11, 29, 47, 67, 80, 102, 122, 148, 169, 191, 217, 254, 258, 266, 273, 290, 310, 321, 341, 345, 352, 367, 381, 399, 419, 437}

func (i Property) String() string {
	if i >= Property(len(_Property_index)-1) {
		return "Property(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Property_name[_Property_index[i]:_Property_index[i+1]]
}
