// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package tokenkind

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Punctuation-0]
	_ = x[Keyword-1]
	_ = x[Identifier-2]
	_ = x[Literal-3]
	_ = x[Comment-4]
}

const _Kind_name = "PunctuationKeywordIdentifierLiteralComment"

var _Kind_index = [...]uint8{0, 11, 18, 28, 35, 42}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
